apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
    role: master
  name: redis-master
  namespace: prd
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: redis-server
  selector:
    app: redis
    role: master
  type: ClusterIP
