apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: ws-pegass
  name: ws-pegass-deployment
  namespace: prd
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ws-pegass
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ws-pegass
    spec:
      containers:
      - image: slavayssiere/ws_pegass:3.0.2
        imagePullPolicy: IfNotPresent
        name: ws-pegass
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: REDIS_HOST
          value: redis-master
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30